from __future__ import annotations


DOMAINS = {
    "template": "模板槽位、脚本标签、母版占位和模板填充",
    "document": "打开、保存、关闭、文档信息",
    "page": "页面、页面尺寸和页面基础操作",
    "spread": "跨页、跨页布局和跨页范围操作",
    "master": "母版、母版跨页和母版对象",
    "layer": "图层创建、查询、锁定、显示和删除",
    "object": "页面对象、对象组、几何位置、脚本标签",
    "text": "文本框、文本内容、段落和字符操作",
    "graphics": "图片、图形框、适配和基础绘制",
    "style": "段落样式、字符样式、对象样式",
    "export": "PDF、IDML、图片等导出和产物验证",
    "book": "InDesign Book 文件、章节和书籍级同步",
    "presentation": "演示型版面、页面序列和 presentation handler 能力",
    "script": "JSX 文件执行和 stdin 临时脚本",
    "session": "CLI 本地状态、最近文档和最近输出",
    "server": "依赖、后端、InDesign COM 健康检查",
    "skill": "把内置 Agent skill 安装到目标项目",
    "utility": "难以归入以上域的辅助能力",
}


EXACT_TOOL_DOMAINS = {
    "run_jsx_file": "template",
    "inspect_template_blueprint": "template",
    "list_template_blueprints": "template",
    "create_page_with_template": "template",
    "populate_template_slots": "template",
    "execute_indesign_code": "script",
    "help": "utility",
}


NAME_DOMAIN_RULES = [
    ("export_", "export"),
    ("package_", "export"),
    ("create_presentation_", "presentation"),
    ("add_cover_page", "presentation"),
    ("add_section_page", "presentation"),
    ("add_full_bleed_image", "presentation"),
    ("add_image_grid", "presentation"),
    ("master_", "master"),
    ("create_master_", "master"),
    ("delete_master_", "master"),
    ("duplicate_master_", "master"),
    ("apply_master_", "master"),
    ("get_master_", "master"),
    ("detach_master_", "master"),
    ("remove_master_", "master"),
    ("list_spreads", "spread"),
    ("get_spread_", "spread"),
    ("duplicate_spread", "spread"),
    ("move_spread", "spread"),
    ("delete_spread", "spread"),
    ("set_spread_", "spread"),
    ("create_spread_", "spread"),
    ("place_file_on_spread", "spread"),
    ("place_xml_on_spread", "spread"),
    ("select_spread", "spread"),
    ("add_page", "page"),
    ("delete_page", "page"),
    ("duplicate_page", "page"),
    ("navigate_to_page", "page"),
    ("get_page_", "page"),
    ("move_page", "page"),
    ("set_page_", "page"),
    ("adjust_page_", "page"),
    ("resize_page", "page"),
    ("create_page_", "page"),
    ("place_file_on_page", "page"),
    ("place_xml_on_page", "page"),
    ("snapshot_page_", "page"),
    ("delete_page_layout_", "page"),
    ("reframe_page", "page"),
    ("select_page", "page"),
    ("create_layer", "layer"),
    ("set_active_layer", "layer"),
    ("list_layers", "layer"),
    ("create_text_", "text"),
    ("edit_text_", "text"),
    ("create_table", "text"),
    ("populate_table", "text"),
    ("find_replace_text", "text"),
    ("find_text_", "text"),
    ("create_paragraph_style", "style"),
    ("create_character_style", "style"),
    ("apply_paragraph_style", "style"),
    ("apply_character_style", "style"),
    ("create_object_style", "style"),
    ("list_object_styles", "style"),
    ("apply_object_style", "style"),
    ("apply_color", "style"),
    ("create_color_swatch", "style"),
    ("list_color_swatches", "style"),
    ("create_rectangle", "graphics"),
    ("create_ellipse", "graphics"),
    ("create_polygon", "graphics"),
    ("place_image", "graphics"),
    ("get_image_", "graphics"),
    ("create_group", "object"),
    ("ungroup", "object"),
    ("get_group_", "object"),
    ("add_items_to_group", "object"),
    ("remove_items_from_group", "object"),
    ("get_all_page_items", "object"),
    ("get_page_item_", "object"),
    ("move_page_item", "object"),
    ("resize_page_item", "object"),
    ("rotate_page_item", "object"),
    ("delete_page_item", "object"),
    ("set_page_item_", "object"),
    ("get_page_items_by_label", "object"),
    ("set_page_item_label", "object"),
    ("get_document_info", "document"),
    ("create_document", "document"),
    ("open_document", "document"),
    ("save_document", "document"),
    ("close_document", "document"),
    ("preflight_document", "document"),
    ("data_merge", "document"),
    ("get_document_", "document"),
    ("set_document_", "document"),
    ("organize_document_", "document"),
    ("create_document_", "document"),
    ("export_document_", "document"),
    ("save_document_", "document"),
    ("open_cloud_document", "document"),
    ("validate_document", "document"),
    ("cleanup_document", "document"),
]


KEYWORD_DOMAINS = {
    "template": "template",
    "blueprint": "template",
    "slot": "template",
    "document": "document",
    "page": "page",
    "spread": "spread",
    "master": "master",
    "layer": "layer",
    "item": "object",
    "object": "object",
    "group": "object",
    "label": "object",
    "text": "text",
    "paragraph": "style",
    "character": "style",
    "style": "style",
    "graphic": "graphics",
    "image": "graphics",
    "export": "export",
    "pdf": "export",
    "idml": "export",
    "book": "book",
    "presentation": "presentation",
    "session": "session",
    "health": "server",
    "skill": "skill",
    "help": "utility",
}


def infer_domain(tool_name: str, description: str = "") -> str:
    exact = EXACT_TOOL_DOMAINS.get(tool_name)
    if exact:
        return exact
    for prefix, domain in NAME_DOMAIN_RULES:
        if tool_name.startswith(prefix):
            return domain
    haystack = f"{tool_name} {description}".lower()
    for keyword, domain in KEYWORD_DOMAINS.items():
        if keyword in haystack:
            return domain
    return "utility"
